### ISSUE TITLE
Database timeout issues

### ISSUE THREAD

**Issue by timkurvers** [wowserhq/spelunker#15]
After a period of inactivity – at least on my dev machine locally – it seems Spelunker is unable to restore / create database connections correctly:

```
Error: read ETIMEDOUT
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
    --------------------
    at Protocol._enqueue (/Users/timkurvers/Projects/wowserhq/spelunker/packages/spelunker-api/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Connection.query (/Users/timkurvers/Projects/wowserhq/spelunker/packages/spelunker-api/node_modules/mysql/lib/Connection.js:208:25)
```

This may be related to the MySQL server, how it handles idle connections and how Knex – the database client in Spelunker – handles them. Will try to debug this a bit more with `DEBUG=knex:*` to see what's going on.

**Comment by timkurvers** [comment]
Worth mentioning that restarting the API process fixes the connectivity problem.
